/**
 * This file contains all the actions types for the Users Reducer
 */
module.exports = {
  USERS_REQUEST: 'USERS/REQUEST',
  USERS_SUCCESS: 'USERS/SUCCESS',
  USERS_FAILURE: 'USERS/FAILURE',

  USERS_CREATE_REQUEST: 'USERS/CREATE_REQUEST',
  USERS_CREATE_SUCCESS: 'USERS/CREATE_SUCCESS',
  USERS_CREATE_FAILURE: 'USERS/CREATE_FAILURE',

  USERS_UPDATE_REQUEST: 'USERS/UPDATE_REQUEST',
  USERS_UPDATE_SUCCESS: 'USERS/UPDATE_SUCCESS',
  USERS_UPDATE_FAILURE: 'USERS/UPDATE_FAILURE',

  USERS_DELETE_REQUEST: 'USERS/DELETE_REQUEST',
  USERS_DELETE_SUCCESS: 'USERS/DELETE_SUCCESS',
  USERS_DELETE_FAILURE: 'USERS/DELETE_FAILURE',

  USERS_SET_SEARCH: 'USERS/SET_SEARCH'
}
